{
 "title": "Microsoft Azure App Service Plan",
 "description": "Use Azure Monitor to view relevante information of App service",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "DataSource",
    "label": "DataSource:",
    "query": "grafana-azure-monitor-datasource"
   },
   { "name": "ResourceGroup", "label": "Resource Group:", "query": "ResourceGroups()" },
   { "name": "Subscription", "label": "Subscription:", "query": "Subscriptions()" },
   { "name": "Workspace", "label": "Workspace:", "query": "Workspaces()" },
   {
    "name": "ServicePlanResourceName",
    "label": "Resource Name:",
    "query": "ResourceNames($ResourceGroup,Microsoft.Web/serverFarms)"
   }
  ]
 },
 "panels": [
  { "title": "Memory & CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Memory Usage % (max)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "appInsights": {
      "dimension": [ "none" ],
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "spliton": "",
      "timeColumn": "timestamp",
      "timeGrain": "auto",
      "timeGrainType": "auto",
      "yaxis": ""
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series",
      "workspace": "$Workspace"
     },
     "azureMonitor": {
      "aggOptions": [
       "Average",
       "Maximum",
       "Minimum"
      ],
      "aggregation": "Maximum",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimension": "",
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "dimensions": [],
      "metricDefinition": "Microsoft.Web/serverFarms",
      "metricName": "MemoryPercentage",
      "metricNamespace": "microsoft.web/serverfarms",
      "resourceGroup": "$ResourceGroup",
      "resourceName": "$ServicePlanResourceName",
      "timeGrain": "PT1M",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ],
      "top": "10"
     },
     "azureResourceGraph": { "resultFormat": "table" },
     "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
     "subscription": "$Subscription",
     "subscriptions": [ "$Subscription" ]
    }
   ]
  },
  {
   "title": "CPU usage % (max)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "appInsights": {
      "dimension": [ "none" ],
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "spliton": "",
      "timeColumn": "timestamp",
      "timeGrain": "auto",
      "timeGrainType": "auto",
      "yaxis": ""
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series",
      "workspace": "$Workspace"
     },
     "azureMonitor": {
      "aggOptions": [
       "Average",
       "Maximum",
       "Minimum"
      ],
      "aggregation": "Maximum",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimension": "",
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "dimensions": [],
      "metricDefinition": "Microsoft.Web/serverFarms",
      "metricName": "CpuPercentage",
      "metricNamespace": "microsoft.web/serverfarms",
      "resourceGroup": "$ResourceGroup",
      "resourceName": "$ServicePlanResourceName",
      "timeGrain": "PT1M",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ],
      "top": "10"
     },
     "azureResourceGraph": { "resultFormat": "table" },
     "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
     "subscription": "$Subscription",
     "subscriptions": [ "$Subscription" ]
    }
   ]
  },
  {
   "title": "Received bytes (total)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "appInsights": {
      "dimension": [ "none" ],
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "spliton": "",
      "timeColumn": "timestamp",
      "timeGrain": "auto",
      "timeGrainType": "auto",
      "yaxis": ""
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series",
      "workspace": "$Workspace"
     },
     "azureMonitor": {
      "aggOptions": [
       "Average",
       "Maximum",
       "Minimum"
      ],
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimension": "",
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "dimensions": [],
      "metricDefinition": "Microsoft.Web/serverFarms",
      "metricName": "BytesReceived",
      "metricNamespace": "microsoft.web/serverfarms",
      "resourceGroup": "$ResourceGroup",
      "resourceName": "$ServicePlanResourceName",
      "timeGrain": "PT1M",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ],
      "top": "10"
     },
     "azureResourceGraph": { "resultFormat": "table" },
     "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
     "subscription": "$Subscription",
     "subscriptions": [ "$Subscription" ]
    }
   ]
  },
  {
   "title": "Sent bytes (total)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "appInsights": {
      "dimension": [ "none" ],
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "spliton": "",
      "timeColumn": "timestamp",
      "timeGrain": "auto",
      "timeGrainType": "auto",
      "yaxis": ""
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series",
      "workspace": "$Workspace"
     },
     "azureMonitor": {
      "aggOptions": [
       "Average",
       "Maximum",
       "Minimum"
      ],
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimension": "",
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "dimensions": [],
      "metricDefinition": "Microsoft.Web/serverFarms",
      "metricName": "BytesSent",
      "metricNamespace": "microsoft.web/serverfarms",
      "resourceGroup": "$ResourceGroup",
      "resourceName": "$ServicePlanResourceName",
      "timeGrain": "PT1M",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ],
      "top": "10"
     },
     "azureResourceGraph": { "resultFormat": "table" },
     "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
     "subscription": "$Subscription",
     "subscriptions": [ "$Subscription" ]
    }
   ]
  },
  {
   "title": "Disk queue length",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "appInsights": {
      "dimension": [ "none" ],
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "spliton": "",
      "timeColumn": "timestamp",
      "timeGrain": "auto",
      "timeGrainType": "auto",
      "yaxis": ""
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series",
      "workspace": "$Workspace"
     },
     "azureMonitor": {
      "aggOptions": [
       "Average",
       "Maximum",
       "Minimum"
      ],
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimension": "",
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "dimensions": [],
      "metricDefinition": "Microsoft.Web/serverFarms",
      "metricName": "DiskQueueLength",
      "metricNamespace": "microsoft.web/serverfarms",
      "resourceGroup": "$ResourceGroup",
      "resourceName": "$ServicePlanResourceName",
      "timeGrain": "PT1M",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ],
      "top": "10"
     },
     "azureResourceGraph": { "resultFormat": "table" },
     "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
     "subscription": "$Subscription",
     "subscriptions": [ "$Subscription" ]
    }
   ]
  },
  {
   "title": "Http queue length",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "appInsights": {
      "dimension": [ "none" ],
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "spliton": "",
      "timeColumn": "timestamp",
      "timeGrain": "auto",
      "timeGrainType": "auto",
      "yaxis": ""
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series",
      "workspace": "$Workspace"
     },
     "azureMonitor": {
      "aggOptions": [
       "Average",
       "Maximum",
       "Minimum"
      ],
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimension": "",
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "dimensions": [],
      "metricDefinition": "Microsoft.Web/serverFarms",
      "metricName": "HttpQueueLength",
      "metricNamespace": "microsoft.web/serverfarms",
      "resourceGroup": "$ResourceGroup",
      "resourceName": "$ServicePlanResourceName",
      "timeGrain": "PT1M",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ],
      "top": "10"
     },
     "azureResourceGraph": { "resultFormat": "table" },
     "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
     "subscription": "$Subscription",
     "subscriptions": [ "$Subscription" ]
    }
   ]
  }
 ]
}