# config file version
apiVersion: 1

# list of datasources that should be deleted from the database
deleteDatasources:
  - name: Azure Monitor
    orgId: 1

# list of datasources to insert/update depending
# whats available in the database
datasources:
  # <string, required> name of the datasource. Required
- name: Azure Monitor
  # <string, required> datasource type. Required
  type: grafana-azure-monitor-datasource
  # <string, required> access mode. direct or proxy. Required
  access: proxy
  # <int> org id. will default to orgId 1 if not specified
  orgId: 1
  # <string> url
  url: /api/datasources/proxy/2
  # <string> database password, if used
  password:
  # <string> database user, if used
  user:
  # <string> database name, if used
  database:
  # <bool> enable/disable basic auth
  basicAuth: false
  # <string> basic auth username
  basicAuthUser:
  # <string> basic auth password
  basicAuthPassword:
  # <bool> enable/disable with credentials headers
  withCredentials:
  # <bool> mark as default datasource. Max one per org
  isDefault: false
  # <map> fields that will be converted to json and stored in json_data
  jsonData:
    azureAuthType: clientsecret
    cloudName: azuremonitor
    tenantId: sample_tenant_id
    clientId: sample_client_id
    subscriptionId: sample_subscription_id
    logAnalyticsTenantId: sample_tenant_id
    logAnalyticsClientId: sample_client_id
    logAnalyticsSubscriptionId: sample_subscription_id
  secureJsonData:
    clientSecret: sample_client_secret
    logAnalyticsClientSecret: sample_client_secret
  version: 1
  # <bool> allow users to edit datasources from the UI.
  editable: false
